export const types = {
  LOGIN: {
    REQUEST: 'LOGIN.REQUEST',
    SUCCESS: 'LOGIN.SUCCESS',
    FAILURE: 'LOGIN.FAILURE',
  },
  LOGIN_WITH_EMAIL: {
    REQUEST: 'LOGIN_WITH_EMAIL.REQUEST',
    SUCCESS: 'LOGIN_WITH_EMAIL.SUCCESS',
    FAILURE: 'LOGIN_WITH_EMAIL.FAILURE',
  },
  LOGOUT: {
    REQUEST: 'LOGOUT.REQUEST',
    SUCCESS: 'LOGOUT.SUCCESS',
    FAILURE: 'LOGOUT.FAILURE',
  },
  REGISTER_WITH_EMAIL: {
    REQUEST: 'REGISTER_WITH_EMAIL.REQUEST',
    SUCCESS: 'REGISTER_WITH_EMAIL.SUCCESS',
    FAILURE: 'REGISTER_WITH_EMAIL.FAILURE',
  },
  PASSWORD_CHANGE: {
    REQUEST: 'PASSWORD_CHANGE.REQUEST',
    SUCCESS: 'PASSWORD_CHANGE.SUCCESS',
    FAILURE: 'PASSWORD_CHANGE.FAILURE',
  },
  PASSWORD_FORGET: {
    REQUEST: 'PASSWORD_FORGET.REQUEST',
    SUCCESS: 'PASSWORD_FORGET.SUCCESS',
    FAILURE: 'PASSWORD_FORGET.FAILURE',
  },
  SYNC_USER: 'SYNC_USER',
};
